#mybatis配置
mybatis:
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  config-location:
  mapper-locations: classpath:mapper/*.xml
#spring配置
spring:
  application:
    name: Spring-Cloud-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#server
server:
  port: 8001

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/